force-app/main/default/objects/A__c/A__c.object-meta.xml
<CustomObject>
    <label>A</label>
    <nameField>
        <label>A Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>A</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/B__c/B__c.object-meta.xml
<CustomObject>
    <label>B</label>
    <nameField>
        <label>B Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/B__c/fields/A__c.field-meta.xml
<CustomField>
    <fullName>A__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>A</label>
    <referenceTo>A__c</referenceTo>
    <relationshipLabel>B</relationshipLabel>
    <relationshipName>B</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/C__c/C__c.object-meta.xml
<CustomObject>
    <label>C</label>
    <nameField>
        <label>C Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>C</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/C__c/fields/B__c.field-meta.xml
<CustomField>
    <fullName>B__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>B</label>
    <referenceTo>B__c</referenceTo>
    <relationshipLabel>C</relationshipLabel>
    <relationshipName>C</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RelatedRecordsTableControllerTest.cls
/**
 * Test class for RelatedRecordsTableController
 * @author LeonardoKipper
 */
@isTest
private class RelatedRecordsTableControllerTest {

    @TestSetup
    static void insertRecords(){
        List<A__c> aLst = new List<A__c>();
        List<B__c> bLst = new List<B__c>();
        List<C__c> cLst = new List<C__c>();
        for(Integer count = 0; count < 3; count++){
            aLst.add(new A__c(Name = 'A.'+count));
            cLst.add(new C__c(Name = 'C.'+count));
        }
        insert aLst;

        for(Integer count = 0; count < 4997; count++){
            if (math.mod(count, 5) == 0){
                bLst.add(new B__c(Name = 'B.'+count, A__c = aLst[0].Id));
            } else if (math.mod(count, 2) == 0) {
                bLst.add(new B__c(Name = 'B.'+count, A__c = aLst[1].Id));
            } else {
                bLst.add(new B__c(Name = 'B.'+count, A__c = aLst[2].Id));
            }
        }
        insert bLst;

        for(Integer count = 0; count < 4997; count++){
            if (math.mod(count, 5) == 0){
                cLst.add(new C__c(Name = 'C.'+count, B__c = bLst[0].Id));
            } else if (math.mod(count, 2) == 0) {
                cLst.add(new C__c(Name = 'C.'+count, B__c = bLst[1].Id));
            } else {
                cLst.add(new C__c(Name = 'C.'+count, B__c = bLst[2].Id));
            }
        }
        insert cLst;
    }

    /**
     * Test method for checkTotalRecords
     * @author LeonardoKipper
     */
    @IsTest
    static void checkTotalRecords(){
        A__c aRecord = [SELECT Id, (SELECT Id FROM B__r) FROM A__c ORDER BY Id ASC LIMIT 1];
        Test.startTest();
            List<Integer> totalRecordsLst = RelatedRecordsTableController.checkTotalRecords(aRecord.Id);
            System.assertEquals(aRecord.B__r.size(), totalRecordsLst[0]);
            System.assertEquals(1000, totalRecordsLst[0]);
            System.assertEquals(1000, totalRecordsLst[0]);
        Test.stopTest();
    }

    /**
     * Test method for getRecordsById
     * @author LeonardoKipper
     */
    @IsTest
    static void getRecordsById(){
        //First A record has 1000 B childs and 1000 C childs.
        A__c aRecord = [SELECT Id, (SELECT Id FROM B__r) FROM A__c Order By Id ASC LIMIT 1];
        Test.startTest();
            List<sObject> relatedObjs = RelatedRecordsTableController.getRecordsById(aRecord.Id, null, false);
            System.assertEquals(RelatedRecordsTableController.retrieveLimit, relatedObjs.size());
            relatedObjs = RelatedRecordsTableController.getRecordsById(aRecord.Id, null, true);
            System.assertEquals(RelatedRecordsTableController.retrieveLimit, relatedObjs.size());
        Test.stopTest();
    }
}